//Sidebar reducer
export const SET_LAST_REGISTERED_USERS = "SET_LAST_REGISTERED_USERS"

//Auth reducer
export const SET_USER_DATA = "SET_USER_DATA"

//Friends reducer
export const TOGGLE_FOLLOWING = "TOGGLE_FOLLOWING"
export const TOGGLE_GETTING_DATA ="TOGGLE_GETTING_DATA"
export const SET_TOTAL_USERS_COUNT="SET_TOTAL_USERS_COUNT"
export const CURRENT_PAGE = "CURRENT_PAGE"
export const HIDE_FRIEND_ITEM = "HIDE_FRIEND_ITEM"
export const CHANGE_SUBSCRIBE_STATUS = "CHANGE_SUBSCRIBE_STATUS"
export const LOAD_USERS = "LOAD_USERS"
export const UPDATE_SEARCH_INPUT_TEXT="UPDATE_SEARCH_INPUT_TEXT"


//Profile reducer
export const LOAD_PROFILE = 'LOAD_PROFILE';
export const ADD_POST = 'ADD_POST'
export const UPDATE_TEXT = 'UPDATE_TEXT'
export const SET_STATUS = 'SET_STATUS'
export const LOAD_AVATAR_IMAGE_OK = 'LOAD_AVATAR_IMAGE_OK'